version: '3.5'
services:
    rabbitmq:
        image: rabbitmq:3.9-management
        container_name: rabbitmq
        volumes:
            - ./rabbitmq/data:/var/lib/rabbitmq #数据文件挂载
            - ./rabbitmq/log:/var/log/rabbitmq #日志文件挂载
        ports:
            - 5672:5672
            - 15672:15672
      
    redis:
        image: redis:5
        restart: always
        container_name: redis
        ports:
            - "6379:6379"
        volumes:
            - "./redis/data:/data"
        command: ["redis-server", "--appendonly", "yes"]
    mysql:
        image: mariadb:10
        restart: always
        container_name: mysql
        env_file:
            - ".env"
        environment:
            - MYSQL_DATABASE=${MYSQL_DATABASE}
            - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
            - MYSQL_USER=${MYSQL_USER}
            - MYSQL_PASSWORD=${MYSQL_PASSWORD}
        ports:
            - "13306:3306"
        volumes:
#            #- "/etc/timezone:/etc/timezone:ro"
            - "./mysql/db:/var/lib/mysql"
