spring:
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  datasource:
    url: jdbc:mysql://localhost:3306/emog?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&useSSL=false
    #url: jdbc:mysql://192.168.1.167:33069/emog?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&useSSL=false
    username: root
    password: root
    #password: testing123
    #password: PXDN93VRKUm8TeE7 # cookie
server:
  port: 8081
  servlet:
    context-path: /api

redis:
  host: localhost
  database: 0
  port: 6379
  password:
  key:
    admin: 'ums:admin'
  expire:
    common: 86400 # 24小时

# mybatis-spring-boot-starter 打印sql执行日志
logging:
  level:
    com:
      emog:
        mapper: debug

# 分页配置，分页类型为mysql
pagehelper:
  helper-dialect: mysql
  # 分页合理话参数，pageNum<=0时查询第一页，pageNum>pages（页面总数），查询最后一页
  reasonable: true


#mybatis:
#  mapper-locations:
##    - classpath:dao/*.xml
#    - classpath*:com/**/mapper/*.xml

# 访问swagger:   http://localhost:8081/swagger-ui/index.html
#  or http://localhost:8081/swagger-ui.html

secure:
  ignored:
    urls: #安全路径白名单
      - /swagger-ui/
#      - /swagger-resources/**
#      - /**/v2/api-docs
#      - /**/*.html
#      - /**/*.js
#      - /**/*.css
#      - /**/*.png
#      - /**/*.map
#      - /favicon.ico
#      - /actuator/**
#      - /druid/**
      - /admin/login
#      - /admin/register
#      - /admin/info
#      - /admin/logout
#      - /minio/upload
      - /**
jwt:
  tokenHeader: Authorization #JWT存储的请求头
  secret: emog-admin-secret #JWT加解密使用的密钥
  expiration: 604800 #JWT的超期限时间(60*60*24*7)
  tokenHead: 'Bearer '  #JWT负载中拿到开头

rabbitmq:
  host: localhost # rabbitmq的连接地址
  port: 5672 # rabbitmq的连接端口号
  virtual-host: /emog # rabbitmq的虚拟host
  username: emog # rabbitmq的用户名
  password: emog # rabbitmq的密码
  publisher-confirms: true #如果对异步消息需要回调必须设置为true


  